:sourcesdir: ../../source

[[release_notes]]
== 发行说明

版本 9::
+
--
. *破坏性更改*：Studio 现在使用 HSQL 2.4.1。当打开一个使用 HSQL 数据库的项目时，Studio 会提示升级项目文件 `build.gradle` 中的 HSQL 版本。如果同意，项目可以正确的用 Studio v.9+ 继续工作。但是，要注意以下问题：
.. 带有新 HSQL 驱动的应用程序如果在带有旧 HSQL 驱动的之前版本 Studio 打开的话，有可能启动不了。
.. 基于 CUBA 7.1 之前的使用 HSQL 的项目，计划任务会失效，因为之前版本的数据库表有一列叫 `PERIOD`，现在在 HSQL 2.4.1 中已经是保留字了。在 CUBA 7.1 里面重命名了该列。

. 热部署机制现在能同时部署更改的类依赖的所有类，这样不会在打开修改了的界面时弹出 `ClassCastException`。

. 当选择 MySQL 或者 Oracle 数据库时，Studio 会展示一个对话框，这里可以点击链接到供应商网站下载 JDBC 驱动，然后可以上传驱动至项目和 Studio。上传驱动结束后，需要重启 Studio。
+
可以使用 *CUBA > Database Proprietary Drivers* 配置页移除上传的驱动。

. 在 *Create CUBA Screen* 向导中可以在浏览界面和主从界面模板的 *Table type* 字段选择 `DataGrid` 和 `TreeDataGrid`。

. 在 *Create CUBA Screen* 向导 添加了 *Extend an existing screen* 和 *Entity fragment* 模板。

. 在可视化编辑器中 Undo/Redo 操作能正常工作。

. 在界面设计器中，数据加载器的查询语句添加了自动完成功能。

. 界面设计器在画布右上角添加了一个按钮，用来切换至界面控制器。

. 在基于新 API 的界面 XML 描述中使用 `invoke` 和 `datasource` 属性时，会给出警告。

. 如果在 *Project Properties* 窗口添加了 Groovy 支持，则可以在 *Create CUBA Screen* 向导中的 *Advanced > Controller language* 字段选择 Groovy。

. Groovy 写的 Services 能在 CUBA 项目树中显示。

. 项目打开时会弹出有框架新版本的提示。

. 微调了代码编辑器中侧边栏的图标。

. 不管有没有重构，都可以在实体设计界面自由更改实体属性的类型。

. 添加了枚举类型设计界面。

. 视图设计器使用原生 IntelliJ UI 重写。

. 数据模型生成器包含使用新 API 的界面模板。

. 所有解决了的问题：

** pass:macros[https://youtrack.cuba-platform.com/issues/STUDIO?q=Milestone:%20%7BRelease%209%7D%20State:%20Fixed,Verified[Studio 9.0 解决的问题\]]
--

版本 8::
+
--
. 现在第一次打开项目是通过导入向导来做了。参阅<<open_project>>了解细节。

. 项目模型现在保存在 `.idea` 文件夹的一个文件内，所以不会每次在打开项目时进行 Gradle 同步。

. 通过 *Run/Debug Configuration* 编辑器现在可以选择运行应用程序服务的 JDK 版本。在 *Configuration* 标签页有 *JVM* 字段。默认使用 `JAVA_HOME` 环境变量的值。

. 可以通过标准的 *Refactor > Rename* 操作来对视图进行重命名。在 CUBA 项目树中可以在视图元素上调用这个操作，也可以在 `views.xml` 文件的视图 XML 定义中的 `name` 属性调用这个操作或者在界面 XML 描述中任何引用该视图的地方调用。

. 可以在界面设计器中数据容器的 *view* 字段调用视图编辑器。

. 实现了在界面描述的 `<fragment>` XML 元素中对 `screen` 属性的自动完成功能以及使用参考功能。

. 为菜单标题实现了本地化名称编辑器。在 CUBA 项目树中点击 *Generic UI > Web Menu*，切换到 *Structure* 标签页，选择一个菜单项然后在 *Caption* 字段点击 *edit* 即可。

. 如果枚举值没有本地化名称，编辑器则会出现警告。如果发现该警告，可以使用 *Create message in the message bundle* 快速修复来创建默认名称。

. 实现了在配置接口中声明应用程序属性时，能自动完成其名称。当定义 `app.properties` 或 `web-app.properties` 内的属性时，按下 Ctrl+Space 即可。

. 所有解决了的问题：

** pass:macros[https://youtrack.cuba-platform.com/issues/STUDIO?q=Fixed%20in%20builds:%208.2.*[Studio 8.2 解决的问题\]]

** pass:macros[https://youtrack.cuba-platform.com/issues/STUDIO?q=Fixed%20in%20builds:%208.0.*%20Fixed%20in%20builds:%208.1.*[Studio 8.0-8.1 解决的问题\]]
--

版本 7::
+
--
. 如果你的项目基于 CUBA 6.10 ，并使用了 BPM 、图表 、全文搜索或报表等高级扩展组件，则需要在 `~/.gradle/gradle.properties` 文件中设置 premium 仓库的访问凭据，如 {main_man_url}/access_to_repo.html#access_to_premium_repo[开发人员手册]所述。 Studio不会将凭据传递给Gradle。

. 所有解决了的问题：

** pass:macros[https://youtrack.cuba-platform.com/issues/STUDIO?q=Fixed%20in%20builds:%207.3.*%20Fixed%20in%20builds:%207.4.*[Studio 7.3-7.4 解决的问题\]]

** https://youtrack.cuba-platform.com/issues/STUDIO?q=Milestone:%20%7BRelease%207%7D%20State:%20Fixed,%20Verified%20Fix%20versions:%207.2%20Affected%20versions:%20-SNAPSHOT%20sort%20by:%20created%20asc[Studio 7.2 解决的问题]

** https://youtrack.cuba-platform.com/issues/STUDIO?q=Milestone:%20%7BRelease%207%7D%20State:%20Fixed,%20Verified%20Fix%20versions:%207.0%20Fix%20versions:%207.1%20Affected%20versions:%20-SNAPSHOT%20sort%20by:%20created%20asc[Studio 7.0-7.1 解决的问题]
--

:sectnums:
