:sourcesdir: ../../../source

[[create_project]]
=== 创建一个新项目

CUBA Studio 提供了一种从零开始创建新 CUBA 项目的简单方法。只需使用 *New Project* 向导，然后按照以下步骤操作：

. 在 *Welcome to CUBA Studio* 窗口中，单击 *Create New Project* 或使用主菜单 *File* -> *New* -> *Project*。

. 选择 *CUBA Project*.

. 指定 *Project namespace*，该命名空间将会作为实体或者数据库表的前缀。命名空间只能由拉丁字母组成，并且尽可能短。*这里需要仔细考虑该名称*，因为之后如果想修改会需要很多手动操作。

. 如果需要，可以修改 *Root package*。这是 Java 类的根包名。也可以之后再调整，但是项目创建阶段生成的类还会使用当前的包名。

. 如果需要，可以修改 *Module prefix*。CUBA 项目的模块名称会添加这个作为前缀。模块名前缀可以稍后修改。

. 在 *Project SDK* 字段，选择对应环境中设置 `JAVA_HOME` 的 JDK。如果看到 `<No SDK>` 这样的值，点击 *New* 然后选择 JDK 安装的目录，比如在 Windows 是 `++C:\Java\jdk8u202-b08++`，macOS 是 `/Library/Java/JavaVirtualMachines/jdk8u202-b08/Contents/Home`。

. 选择默认仓库配置，或为项目 {main_man_url}/access_to_repo.html[自定义] 仓库配置。

. 选择项目中使用的 *Platform version*。如果没有特别需求，使用最新的发布版本。

. 为了做 beta 测试或尝试使用新的 CUBA 平台功能，您也许需要使用一个不稳定的 CUBA 版本，即，以 `BETA` 或 `SNAPSHOT` 结尾的版本。需要勾选 *Show unstable versions* 复选框，才能在 *Platform version* 的下拉框中看到这些版本。注意，`SNAPSHOT` 发行版只在 `repo.cuba-platform.com` 仓库发布。

. 在 *Languages support* 下拉框字段选择项目使用的编程语言，或者使用默认的 *Java* 语言。

. 使用 *Available locales* 字段打开 *Locales* 编辑器对话框，可以为项目添加多地区支持。也可以稍后再修改该配置。

. 点击 *Next*。

. 向导的第二步中，可以配置主数据存储属性，比如，为新项目选择本地的 PostgreSQL 作为数据库。这些属性也可以稍后修改。

. 点击 *Next*。

. 如果需要，可以修改 *Project name* 字段的值。该名称只能包含拉丁字母、数字和下划线。

. *Project location* 配置新项目的路径。可以输入其他的值或者点击省略号按钮修改这个路径。

. 单击 *Finish*。空项目将在指定目录中创建，之后 Studio 会自动通过 Gradle 文件开始构建项目信息并为项目建立索引。

. 项目同步和建立索引过程完成后，将在 *Project* 工具窗口中看到 CUBA 项目树。

. 打开 *Gradle* 工具窗口，默认固定在右边栏。点击“扳手”图标（*Gradle Settings*）然后在 *Gradle JVM* 字段选择 `Use JAVA_HOME`。如果在下拉列表中没有看到该选项，请确保按照 CUBA 开发者手册中 {main_man_url}/setup.html[安装] 部分配置了正确的开发环境。点击 *OK*。

. 现在可以开始项目的工作了。
